spring.application.name=stayZen

#DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/stayZen
spring.datasource.username=postgres
spring.datasource.password=Yash@5112
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
